/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type ShowPetByIdRequest = {
    /**
     * The id of the pet to retrieve
     */
    petId: string;
};

export type ShowPetByIdResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Expected response to a valid request
     */
    pet?: components.Pet | undefined;
    /**
     * unexpected error
     */
    error?: components.ErrorT | undefined;
};

/** @internal */
export namespace ShowPetByIdRequest$ {
    export type Inbound = {
        petId: string;
    };

    export const inboundSchema: z.ZodType<ShowPetByIdRequest, z.ZodTypeDef, Inbound> = z
        .object({
            petId: z.string(),
        })
        .transform((v) => {
            return {
                petId: v.petId,
            };
        });

    export type Outbound = {
        petId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ShowPetByIdRequest> = z
        .object({
            petId: z.string(),
        })
        .transform((v) => {
            return {
                petId: v.petId,
            };
        });
}

/** @internal */
export namespace ShowPetByIdResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        Pet?: components.Pet$.Inbound | undefined;
        Error?: components.ErrorT$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<ShowPetByIdResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            Pet: components.Pet$.inboundSchema.optional(),
            Error: components.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.Pet === undefined ? null : { pet: v.Pet }),
                ...(v.Error === undefined ? null : { error: v.Error }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        Pet?: components.Pet$.Outbound | undefined;
        Error?: components.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ShowPetByIdResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            pet: components.Pet$.outboundSchema.optional(),
            error: components.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.pet === undefined ? null : { Pet: v.pet }),
                ...(v.error === undefined ? null : { Error: v.error }),
            };
        });
}
